# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d6cd1a032a4410757d0528c403a59a4987600d37d93778f1543485c28ddf939594b6629b2c67414047b5bf4967c0de60615e6a9fc405113932ac7429a31f66c

test:
  secret_key_base: 87242fbceede36e5257c3b4fcf5a535f4e89aecc0dab4552a74df3c42e8ce0d2686bfba9e1b9ddfab5e8f937c6df75834502adc9fdd6d01757e0a0b600bbd616

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
